language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup install nightly
  - cargo +nightly install --force rustfmt-nightly

script:
  - cargo +nightly fmt -- --write-mode=diff
  - cargo build --verbose
  - cargo test --verbose

matrix:
  allow_failures:
    - rust: nightly
