[package]

name = "gpx"
description = "Rust read/write support for GPS Exchange Format (GPX)"
license = "MIT"
version = "0.4.1"
authors = ["Brendan Ashworth <brendan.ashworth@me.com>", "Corey Farwell <coreyf@rwell.org>"]
readme = "README.md"
documentation = "https://docs.rs/gpx"
repository = "https://github.com/georust/gpx"

[dependencies]
geo-types = "0.2"
xml-rs = "0.8"
chrono = "0.4"
error-chain = "0.11.0"
assert_approx_eq = "1.0.0"

[dev-dependencies]
geo = "0.10"
